# -*- coding: utf-8 -*-
"""function_V2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ov4_2YDA28E7CPOpkNTosi2cVjfTxFOQ
"""

import os
import joblib
import pandas as pd
import numpy as np
from scipy.sparse import hstack as sparse_hstack, csc_matrix
from sklearn.metrics.pairwise import cosine_similarity

# Inisialisasi variabel global tunggal untuk menampung semua artifak
api_artifacts = None

def load_models_on_startup():
    global api_artifacts

    try:
        print("Memuat satu file model dan data API...")

        # Mengatur path dinamis berdasarkan lokasi file ini berada
        base_dir = os.path.dirname(os.path.abspath(__file__))
        artifacts_dir = os.path.join(base_dir, 'artifacts')

        # Menentukan path absolut untuk file pkl tunggal kita
        model_path = os.path.join(artifacts_dir, "model_rekomendasi.pkl")

        # Proses loading seluruh artifak dari satu file
        api_artifacts = joblib.load(model_path)

        print("Semua komponen model dan data berhasil dimuat dari satu file .pkl.")

    except Exception as e:
        print(f"Gagal memuat file pkl tunggal pada startup: {e}")


# =========================================================
# FUNGSI REKOMENDASI UTAMA UNTUK API (VERSI MULTI-PREDIKTOR)
# =========================================================

def get_recommendations(
    selected_genres: list,
    director_input: str = None,
    year_input: int = None,
    num_recommendations: int = 10
):
    global api_artifacts

    # =====================================================
    # 1. VALIDASI INPUT & KONDISI MODEL
    # =====================================================
    # Genre wajib diisi dan harus berupa list (1 sampai 3 genre)
    if not selected_genres or not isinstance(selected_genres, list):
        return {
            "success": False,
            "message": "selected_genres wajib diisi dan harus berupa list (bisa 1 hingga 3 genre).",
            "data": []
        }

    if api_artifacts is None:
        return {
            "success": False,
            "message": "Model belum dimuat di server. Pastikan load_models_on_startup() sudah dijalankan.",
            "data": []
        }

    try:
        # Ekstrak komponen dari dictionary tunggal api_artifacts
        df_movies = api_artifacts['df_movies']
        feature_matrix = api_artifacts['feature_matrix']
        tfidf_genre = api_artifacts['tfidf_vectorizer']
        tfidf_director = api_artifacts['tfidf_director']
        scaler = api_artifacts['scaler']

        # =====================================================
        # 2. PROSES VEKTORISASI INPUT USER (DINAMIS & OPSIONAL)
        # =====================================================

        # A. Proses Genre (Wajib: 1-3 genre)
        # Gabungkan list genre pilihan user menjadi satu string (space-separated)
        selected_genres_str = " ".join(selected_genres)
        genre_vector_input = tfidf_genre.transform([selected_genres_str])

        # B. Proses Director (Opsional)
        if director_input and str(director_input).strip():
            director_vector_input = tfidf_director.transform([director_input])
        else:
            # Jika user tidak memasukkan director, buat matriks bernilai 0 (netral)
            director_vocab_size = tfidf_director.transform(['']).shape[1]
            director_vector_input = csc_matrix((1, director_vocab_size))

        # C. Proses Fitur Numerik (IMDB, Runtime, Year Premier)
        # Ambil nilai median default dari dataset untuk data yang netral/tidak diinput user
        default_imdb = df_movies['IMDB Score'].median()
        # Hitung runtime_normalized dari kolom Runtime (karena tidak tersimpan di df_movies)
        min_runtime = df_movies['Runtime'].min()
        max_runtime = df_movies['Runtime'].max()
        df_movies['runtime_normalized'] = (df_movies['Runtime'] - min_runtime) / (max_runtime - min_runtime)
        default_runtime = df_movies['runtime_normalized'].median()

        # Cek jika user memasukkan input year_premiere, jika tidak gunakan median dataset
        chosen_year = int(year_input) if year_input else df_movies['year_premiere'].median()

        # Gunakan scaler untuk menormalisasi nilai numerik input.
        # Catatan: Scaler kita di-fit menggunakan susunan kolom [IMDB Score, runtime_normalized, year_premiere]
        user_numeric_scaled = scaler.transform([[default_imdb, default_runtime, chosen_year]])
        user_imdb_scaled = user_numeric_scaled[0][0]
        user_runtime_scaled = user_numeric_scaled[0][1]
        user_year_scaled = user_numeric_scaled[0][2]

        # Jika user TIDAK menginput year_premiere, kita beri nilai year_scaled yang sedikit dinetralkan
        # agar tidak terlalu membiaskan pencarian berbasis kemiripan sudut cosine
        if not year_input:
            user_year_scaled = 0.7  # Nilai ideal profil target agar stabil

        # Ubah fitur numerik menjadi matriks sparse terpisah, lalu disatukan
        numeric_vector_input = sparse_hstack([
            csc_matrix([[user_imdb_scaled]]),
            csc_matrix([[user_runtime_scaled]]),
            csc_matrix([[user_year_scaled]])
        ])

        # D. Gabungkan Seluruh Fitur Input Menjadi Matriks Global Tunggal
        # Susunan harus persis sama dengan notebook: [Genre, Director, Numerik]
        input_feature_matrix = sparse_hstack([
            genre_vector_input,
            director_vector_input,
            numeric_vector_input
        ])

        # =====================================================
        # 3. PERHITUNGAN COSINE SIMILARITY
        # =====================================================

        # Hitung skor kemiripan antara input gabungan user dengan SEMUA film di database
        sim_scores = cosine_similarity(input_feature_matrix, feature_matrix)[0]

        # Ambil indeks film yang memiliki skor kesamaan di atas 0
        movie_scores = [
            (idx, score)
            for idx, score in enumerate(sim_scores)
            if score > 0
        ]

        # Urutkan hasil pencarian dari nilai kemiripan tertinggi (paling relevan)
        movie_scores = sorted(movie_scores, key=lambda x: x[1], reverse=True)

        # Batasi indeks film yang diambil sebanyak nilai num_recommendations
        movie_indices = [idx for idx, score in movie_scores[:num_recommendations]]

        # =====================================================
        # 4. EKSTRAKSI DAN FORMATTING DATA FILM
        # =====================================================
        # Kolom output disesuaikan dengan keputusan tim (main_parent_genre & menyertakan Plot)
        kolom_output = [
            "Title",
            "main_parent_genre",
            "Director",
            "year_premiere",
            "IMDB Score",
            "Runtime",
            "poster",
            "primary_language_capitalized",
            "Premiere",
            "Plot"
        ]

        # Ambil data film berdasarkan urutan kemiripan terbaik
        recommendations = df_movies[kolom_output].iloc[movie_indices].copy()

        # Tambahkan informasi similarity_score ke dalam dataframe hasil
        recommendations["similarity_score"] = [
            round(score, 4) for idx, score in movie_scores[:num_recommendations]
        ]

        # Kembalikan response sukses dalam format dict/JSON-friendly
        return {
            "success": True,
            "message": "Rekomendasi berhasil dibuat.",
            "total": len(recommendations),
            "data": recommendations.to_dict(orient="records")
        }

    except Exception as e:
        # Menangkap error internal agar API tidak mengalami crash total (HTTP 500)
        return {
            "success": False,
            "message": f"Terjadi error pada internal function: {str(e)}",
            "data": []
        }