# -*- coding: utf-8 -*-
"""function.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CcYay7froip17A6D8s9pKh5kNqshBWhV
"""

import joblib
import pandas as pd
import numpy as np

from scipy.sparse import hstack as sparse_hstack
from sklearn.metrics.pairwise import cosine_similarity

api_tfidf_vectorizer = None
api_feature_matrix = None
api_df_movies = None

def load_models_on_startup():
    global api_tfidf_vectorizer
    global api_feature_matrix
    global api_df_movies

    try:
        print("Memuat model dan data API...")

        api_tfidf_vectorizer = joblib.load(
            "api_tfidf_vectorizer.pkl"
        )

        api_feature_matrix = joblib.load(
            "api_feature_matrix.pkl"
        )

        api_df_movies = pd.read_pickle(
            "api_df_movies.pkl"
        )

        print("Model dan data berhasil dimuat.")

    except Exception as e:
        print(f"Gagal memuat model/data: {e}")


# =========================================================
# FUNGSI REKOMENDASI
# =========================================================

def get_recommendations(
    selected_genres: list,
    num_recommendations: int = 10
):
    """
    Menghasilkan rekomendasi film berdasarkan genre.

    Parameters
    ----------
    selected_genres : list
        List genre pilihan user.
        Contoh:
        ['action', 'comedy']

    num_recommendations : int
        Jumlah rekomendasi yang ingin ditampilkan.

    Returns
    -------
    list[dict]
        Hasil rekomendasi dalam format JSON-friendly.
    """

    global api_tfidf_vectorizer
    global api_feature_matrix
    global api_df_movies

    # =====================================================
    # VALIDASI INPUT
    # =====================================================

    if not selected_genres:
        return {
            "success": False,
            "message": "Genre tidak boleh kosong.",
            "data": []
        }

    if not isinstance(selected_genres, list):
        return {
            "success": False,
            "message": "selected_genres harus berupa list.",
            "data": []
        }

    # =====================================================
    # CEK MODEL SUDAH DIMUAT
    # =====================================================

    if any(v is None for v in [
        api_tfidf_vectorizer,
        api_feature_matrix,
        api_df_movies
    ]):
        return {
            "success": False,
            "message": "Model belum dimuat.",
            "data": []
        }

    # =====================================================
    # PROSES REKOMENDASI
    # =====================================================

    try:

        # ---------------------------------------------
        # Gabungkan genre input user
        # ---------------------------------------------

        selected_genres_str = " ".join(selected_genres)

        # ---------------------------------------------
        # Transform input genre ke TF-IDF vector
        # ---------------------------------------------

        genre_vector_input = api_tfidf_vectorizer.transform(
            [selected_genres_str]
        )

        # ---------------------------------------------
        # Hitung jumlah fitur numerik tambahan
        # ---------------------------------------------

        num_tfidf_cols = len(
            api_tfidf_vectorizer.get_feature_names_out()
        )

        num_numeric_cols = (
            api_feature_matrix.shape[1]
            - num_tfidf_cols
        )

        # ---------------------------------------------
        # Dummy fitur numerik
        # ---------------------------------------------

        dummy_numeric_features = np.zeros(
            (1, num_numeric_cols)
        )

        # ---------------------------------------------
        # Gabungkan TF-IDF + fitur numerik
        # ---------------------------------------------

        input_feature_matrix = sparse_hstack([
            genre_vector_input,
            dummy_numeric_features
        ])

        # ---------------------------------------------
        # Hitung cosine similarity
        # ---------------------------------------------

        sim_scores = cosine_similarity(
            input_feature_matrix,
            api_feature_matrix
        )[0]

        # ---------------------------------------------
        # Ambil film dengan similarity > 0
        # ---------------------------------------------

        movie_scores = [
            (idx, score)
            for idx, score in enumerate(sim_scores)
            if score > 0
        ]

        # ---------------------------------------------
        # Urutkan berdasarkan similarity tertinggi
        # ---------------------------------------------

        movie_scores = sorted(
            movie_scores,
            key=lambda x: x[1],
            reverse=True
        )

        # ---------------------------------------------
        # Ambil top-N rekomendasi
        # ---------------------------------------------

        movie_indices = [
            idx
            for idx, score
            in movie_scores[:num_recommendations]
        ]

        # ---------------------------------------------
        # Ambil data film
        # ---------------------------------------------

        recommendations = api_df_movies[
            [
                "Title",
                "parent_genre_str",
                "IMDB Score",
                "Runtime",
                "poster",
                "Language",
                "Premiere"
            ]
        ].iloc[movie_indices]

        # ---------------------------------------------
        # Tambahkan similarity score (opsional)
        # ---------------------------------------------

        recommendations = recommendations.copy()

        recommendations["similarity_score"] = [
            round(score, 4)
            for idx, score
            in movie_scores[:num_recommendations]
        ]

        return {
            "success": True,
            "message": "Rekomendasi berhasil dibuat.",
            "total": len(recommendations),
            "data": recommendations.to_dict(
                orient="records"
            )
        }

    except Exception as e:

        return {
            "success": False,
            "message": f"Terjadi error: {str(e)}",
            "data": []
        }